version: "3.4"

services:
  deepwork-backend:
    image: nginx
    container_name: deepwork-backend
    restart: unless-stopped  
    #ports:
    #  - 80:80
    expose:
        - "80"
    volumes:
      - ./_site:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      traefik-homelab:
    labels:
        - "traefik.enable=true"
        - 'traefik.http.routers.deepwork-backend.entrypoints=https'
        - "traefik.http.routers.deepwork-backend.rule=Host(`deepwork.${MY_DOMAIN}`)" # CHANGE THIS IF YOU WANT
        - "traefik.http.routers.deepwork-backend.tls.certresolver=myresolver"
        - "traefik.http.routers.deepwork-backend.service=deepwork-backend@docker"
        - "traefik.http.services.deepwork-backend.loadbalancer.server.port=80"
        - "traefik.http.routers.deepwork-backend.tls.options=default"
        - "traefik.docker.network=traefik-homelab"
        # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        - "traefik.http.middlewares.test-auth.basicauth.users=user:$$apr1$$T3qH6Aa2$$DrRzHczCyMfdfb7CLf7qX1" # user password
        - "traefik.http.routers.deepwork-backend.middlewares=test-auth"
networks:
  traefik-homelab:
    external:
      name: traefik-homelab
